config/routes.rb
Rails.application.routes.draw do
  get 'help/builders'
  get 'help/recipes'
  get 'help/repos'
  get 'help/builds'
  get 'help', to: 'help#index'

  mount API::Root => '/'

  resources :builds
  resources :builders

  get '/builders/:hostname/getwork', to: 'builders#getwork'
  post '/builders/:hostname/putwork', to: 'builders#putwork'
  #match '/builders(/:hostname)/getwork', :action => 'getwork', via: [:get], :controller => :builders

  resources :repos
  resources :recipes, only: [:index, :show], id: /[A-Za-z0-9\.\-_\+~]+?/, format: false

  root 'recipes#index'
end

app/models/repo.rb
class Repo < ActiveRecord::Base
  validates_presence_of :name, message: 'is missing'
  validates_format_of :url, with: /(http(?:s)?\:\/\/[a-zA-Z0-9\-]+(?:\.[a-zA-Z0-9\-]+)*\.[a-zA-Z]{2,6}(?:\/?|(?:\/[\w\-]+)*)(?:\/?|\/\w+\.[a-zA-Z]{2,4}(?:\?[\w]+\=[\w\-]+)?)?(?:\&[\w]+\=[\w\-]+)*)/i, message: 'is invalid'

  has_many :packages
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_action :set_repo, only: [:show, :edit, :update, :destroy]

  # GET /repos
  # GET /repos.json
  def index
    @repos = Repo.all
  end

  # GET /repos/1
  # GET /repos/1.json
  def show
  end

  # GET /repos/new
  def new
    @repo = Repo.new
  end

  # GET /repos/1/edit
  def edit
  end

  # POST /repos
  # POST /repos.json
  def create
    @repo = Repo.new(repo_params)

    respond_to do |format|
      if @repo.save
        format.html { redirect_to @repo, notice: 'Repo was successfully created.' }
        format.json { render :show, status: :created, location: @repo }
      else
        format.html { render :new }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repos/1
  # PATCH/PUT /repos/1.json
  def update
    respond_to do |format|
      if @repo.update(repo_params)
        format.html { redirect_to @repo, notice: 'Repo was successfully updated.' }
        format.json { render :show, status: :ok, location: @repo }
      else
        format.html { render :edit }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repos/1
  # DELETE /repos/1.json
  def destroy
    @repo.destroy
    respond_to do |format|
      format.html { redirect_to repos_url, notice: 'Repo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_repo
    @repo = Repo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def repo_params
    params.require(:repo).permit(:name, :url, :lastrefresh)
  end
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/repos/_form.html.erb
<%= form_for(@repo) do |f| %>
  <% if @repo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repo.errors.count, "error") %> prohibited this repo from being saved:</h2>

      <ul>
      <% @repo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :lastrefresh %><br>
    <%= f.datetime_select :lastrefresh %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repos/edit.html.erb
<h1>Editing repo</h1>

<%= render 'form' %>

<%= link_to 'Show', @repo %> |
<%= link_to 'Back', repos_path %>

app/views/repos/index.html.erb
<div class="title">
  <h2>Repositories</h2>
  <p>This is a listing of package repositories known to the Haiku package build system</p>
</div>

<table style="border: 1px solid black; width: 100%; border-spacing: 0px;">
  <thead>
      <tr style="font-size: 0.8em; text-align: left; background-color: #aaaaaa;">
      <th>Name</th>
      <th>Url</th>
      <th>Lastrefresh</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repos.each do |repo| %>
      <tr style="font-size: 0.9em; background-color: <%= cycle('#eeeeee', '#ffffff') -%>;">
        <td><%= link_to repo.name, repo %></td>
        <td><%= repo.url %></td>
        <td><%= repo.lastrefresh %></td>
        <td><%= link_to 'Edit', edit_repo_path(repo) %></td>
        <td><%= link_to 'Destroy', repo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repo', new_repo_path %>

app/views/repos/new.html.erb
<h1>New repo</h1>

<%= render 'form' %>

<%= link_to 'Back', repos_path %>

app/views/repos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @repo.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @repo.url %>
</p>

<p>
  <strong>Lastrefresh:</strong>
  <%= @repo.lastrefresh %>
</p>

<%= link_to 'Edit', edit_repo_path(@repo) %> |
<%= link_to 'Back', repos_path %>