config/routes.rb
Rails.application.routes.draw do
  get 'help/builders'
  get 'help/recipes'
  get 'help/repos'
  get 'help/builds'
  get 'help', to: 'help#index'

  mount API::Root => '/'

  resources :builds
  resources :builders

  get '/builders/:hostname/getwork', to: 'builders#getwork'
  post '/builders/:hostname/putwork', to: 'builders#putwork'
  #match '/builders(/:hostname)/getwork', :action => 'getwork', via: [:get], :controller => :builders

  resources :repos
  resources :recipes, only: [:index, :show], id: /[A-Za-z0-9\.\-_\+~]+?/, format: false

  root 'recipes#index'
end

app/models/builder.rb
class Builder < ActiveRecord::Base
  has_many :builds
  belongs_to :architecture

  def last_build
    return nil if self.builds.count == 0
    return self.builds.order('id desc').first
  end

  def busy
    return false if self.builds.count == 0
    return (self.builds.order('id desc').first.active == true)
  end
end

app/controllers/builders_controller.rb
class BuildersController < ApplicationController
  before_action :set_builder, only: [:show, :edit, :update, :destroy]
  before_action :set_builder_byhost, only: [:getwork, :putwork]

  # We accept data from outside of the normal rails app
  skip_before_action :verify_authenticity_token, only: [:putwork]

  # GET /builders
  # GET /builders.json
  def index
    @builders = Builder.all
  end

  # GET /builders/1
  # GET /builders/1.json
  def show
  end

  # POST /builders/hostname/putwork 
  def putwork
    if !@builder or params[:token] != @builder['token']
      # Invalid builder or token, redirect to root
      redirect_to '/', notice: 'Invalid builder API call!'
      return
    end

    @builder.update(lastheard: Time.now)
    build = Build.find(params[:build_id])
    build.update(completed: Time.now,
      status: (params[:status] == 'OK') ? 'Success' : 'Failure',
      result: params[:result])

    redirect_to '/'
  end

  # GET /builders/hostname/getwork
  def getwork
    if !@builder or params[:token] != @builder['token']
      # Invalid builder or token, redirect to root
      redirect_to '/', notice: 'Invalid builder API call!'
      return
    end

    @builder.update(lastheard: Time.now)

    workitems = []
    Package.joins(:recipe).where('packages.latestrev < recipes.revision').where(architecture: @builder.architecture).each do |package|

      # Limit to one workitem for now
      # Could this be done in the query?
      next if workitems.count > 0
      next if Build.where(recipe: package.recipe).where(completed: nil).count > 0

      # Schedule the build for this builder
      build = Build.create(architecture: package.architecture,
        builder: @builder, recipe: package.recipe, issued: Time.now,
        status: 'Building')

      # last seen built revision is outdated
      # add work to tasks
      task = {
        id: build[:id],
        name: package.recipe[:name],
        version: package.recipe[:version],
        revision: package.recipe[:revision],
        architecture: @builder.architecture[:name]
      }
      workitems.push(task)
    end
    
    render json: workitems
  end

  # POST /builders
  # POST /builders.json
  def create
    @builder = Builder.new(builder_params)

    respond_to do |format|
      if @builder.save
        format.html { redirect_to @builder, notice: 'Builder was successfully created.' }
        format.json { render :show, status: :created, location: @builder }
      else
        format.html { render :new }
        format.json { render json: @builder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /builders/1
  # PATCH/PUT /builders/1.json
  def update
    respond_to do |format|
      if @builder.update(builder_params)
        format.html { redirect_to @builder, notice: 'Builder was successfully updated.' }
        format.json { render :show, status: :ok, location: @builder }
      else
        format.html { render :edit }
        format.json { render json: @builder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /builders/1
  # DELETE /builders/1.json
  def destroy
    @builder.destroy
    respond_to do |format|
      format.html { redirect_to builders_url, notice: 'Builder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_builder
    @builder = Builder.find(params[:id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_builder_byhost
    @builder = Builder.find_by(hostname: params[:hostname])
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def builder_params
    params.require(:builder).permit(:architecture_id, :hostname, :owner, :location, :lastheard, :token, :result, :status, :build_id)
  end
end

app/helpers/builders_helper.rb
module BuildersHelper
  def heartbeat_info(builder)
    if !builder.lastheard
      return "New builder, no heartbeats"
    end

    age = Time.now.to_i - builder.lastheard.to_i
    if age < 90
      status = "<span style='font-weight: bold; color: #00ff00;'>Online</span>"
      if builder.busy
        state = "<span style='font-weight: bold; color: #00ffff;'>Working</span>"
      else
        state = "<span style='font-weight: bold; color: #cccccc;'>Idle</span>"
      end
      return "#{status}, #{state}"
    end
    return "<span style='font-weight: bold; color: #ffff00;'>Missing for #{time_ago_in_words(builder.lastheard)}</span>"
  end
end

app/views/builders/_form.html.erb
<%= form_for(@builder) do |f| %>
  <% if @builder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@builder.errors.count, "error") %> prohibited this builder from being saved:</h2>

      <ul>
      <% @builder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :architecture_id %><br>
    <%= f.number_field :architecture_id %>
  </div>
  <div class="field">
    <%= f.label :hostname %><br>
    <%= f.text_field :hostname %>
  </div>
  <div class="field">
    <%= f.label :owner %><br>
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :lastheard %><br>
    <%= f.datetime_select :lastheard %>
  </div>
  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/builders/index.html.erb
<p id="notice"><%= notice %></p>

<div class="title">
  <h2>Builders</h2>
  <p>This is a complete listing of build machines leveraged by the Haiku package build system</p>
</div>

<table class="table table-striped table-hover table-condensed" style='width: 100%;'>
  <thead>
    <tr>
      <th>Hostname</th>
      <th>Architecture</th>
      <th>OS Build</th>
      <th>Client Version</th>
      <th>Threads</th>
      <th>Owner</th>
      <th>Location</th>
      <th>State</th>
    </tr>
  </thead>

  <tbody>
    <% @builders.each do |builder| %>
      <tr>
        <td><%=raw builder_icon(builder) %> <%= link_to builder.hostname, builder %></td>
        <td><%= (builder.architecture ? builder.architecture['name'] : "unknown")%></td>
        <td><%= (builder.osbuild or "unknown") %></td>
        <td><%= (builder.client_version or "unknown") %></td>
        <td><%= (builder.threads or "unknown") %></td>
        <td><%= builder.owner.gsub(/.{2}@.{2}/, '##@##') %></td>
        <td><%= link_to builder.location, "https://maps.google.com/maps?q=#{builder.location}", :target => "_blank" %></td>
        <td><%=raw heartbeat_info(builder) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/builders/show.html.erb
<p id="notice"><%= notice %></p>

<div class='row'>
  <div class='col-md-12'>
    <span style="font-size: 1.5em; font-weight: bold;"><%= builder_icon(@builder, 32) %> <%=@builder.hostname %></span> (<%=raw heartbeat_info(@builder) %>)
  </div>
</div> <!-- row -->

<br/>

<div class='row'>
  <div class='col-md-8'>
    <div class="panel panel-default">
    <div class="panel-heading">Builder Info</div>
    <div class="panel-body">
    <table class="table table-striped table-condensed table-hover" style='width: 100%;'>
        <tr><td><b>OS Build</b></td><td><%= @builder.osbuild ? (link_to @builder.osbuild, "http://cgit.haiku-os.org/haiku/tag/?id=#{@builder.osbuild}") : "unknown" %></td></tr>
        <tr><td><b>Architecture</b></td><td><%= @builder.architecture ? @builder.architecture.name : "unknown" %></td></tr>
        <tr><td><b>CPUs</b></td><td><%= @builder.threads ? @builder.threads : "unknown" %></td></tr>
        <tr><td><b>Owner</b></td><td><%= @builder.owner ? @builder.owner : "unknown" %></td></tr>
        <tr><td><b>Last heartbeat</b></td><td><%= @builder.lastheard ? "#{time_ago_in_words(@builder.lastheard)} ago" : "never" %></td></tr>
    </table>
    </div>
    </div>
  </div>
  <div class='col-md-4'>
    <div class="panel panel-default">
    <div class="panel-heading">Location</div>
    <div class="panel-body">
    <img src="https://image.maps.ls.hereapi.com/mia/1.6/mapview?apiKey=bFtu8enqN7PRw2-TAMfDarx_O8riFrkXk8qCcU42Z-4&ci=<%=@builder.location%>&w=324&h=175&z=3&t=14">
    </div>
    </div>
  </div>
</div>

<div class='row'>
  <div class='col-md-12'>
    <div class="panel panel-default">
    <div class="panel-heading">Recent builds</div>
    <div class="panel-body">
    <table class="table table-striped table-hover table-condensed" style='width: 100%;'>
      <thead>
        <tr>
          <th>ID</th>
          <th>Recipe</th>
          <th>Version</th>
          <th>Revision</th>
          <th>Issued</th>
          <th>Completed</th>
          <th>Status</th>
        </tr>
      </thead>

      <tbody>
        <% if @builder.builds.count == 0 %>
          <tr><td COLSPAN=6><i>No known builds</i></td></tr>
        <% end %>
        <% @builder.builds.order('issued DESC').first(10).each do |build| %>
          <tr>
            <td><%= link_to "##{build.id}", build %></td>
            <td><%= link_to build.recipe['name'], build.recipe %></td>
            <td><%= build.recipe['version'] %></td>
            <td><%= build.recipe['revision'] %></td>
            <td><%= build.issued %></td>
            <td><%= build.completed ? build.completed : "never" %></td>
            <td><%=raw build_state(build) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
    </div>
  </div>
</div>


<%= link_to 'Back', builders_path %>