config/routes.rb
Rails.application.routes.draw do
  get 'help/builders'
  get 'help/recipes'
  get 'help/repos'
  get 'help/builds'
  get 'help', to: 'help#index'

  mount API::Root => '/'

  resources :builds
  resources :builders

  get '/builders/:hostname/getwork', to: 'builders#getwork'
  post '/builders/:hostname/putwork', to: 'builders#putwork'
  #match '/builders(/:hostname)/getwork', :action => 'getwork', via: [:get], :controller => :builders

  resources :repos
  resources :recipes, only: [:index, :show], id: /[A-Za-z0-9\.\-_\+~]+?/, format: false

  root 'recipes#index'
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :packages
  has_many :builds
  has_many :architectures, through: :packages

  def self.search(search)
    if search
      # TODO: Better sort version numbers as they are strings
      where('name LIKE ?', "%#{search.downcase}%").order([:category, :name, :version])
    else
      all.order([:category, :name, :version])
    end
  end

  def to_param
    #"#{name}-#{version.parameterize("_")}"
    "#{name}-#{version}"
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  per_page = 10
  before_action :set_recipe, only: [:show]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.search(params[:search]).includes(packages: [:repo, :architecture]).page(params[:page])
    @architectures = Architecture.all.order(:name)
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @architectures = Architecture.all
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    query = params[:id].split('-')
    if !query[1]
      @recipe = Recipe.where(name: query[0]).includes(packages: [:repo, :architecture]).order('version DESC').first
    else
      @recipe = Recipe.includes(packages: [:repo, :architecture]).find_by(name: query[0], version: query[1])
    end
    if !@recipe
      # Invalid builder or token, redirect to root
      redirect_to '/', notice: 'Package by that name not found!'
      return
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(:name, :version, :revision, :filename)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :version %><br>
    <%= f.text_field :version %>
  </div>
  <div class="field">
    <%= f.label :revision %><br>
    <%= f.number_field :revision %>
  </div>
  <div class="field">
    <%= f.label :filename %><br>
    <%= f.text_field :filename %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="title">
  <h2>Recipes</h2>
  <p>This is a complete listing of <a href="http://bitbucket.org/haikuports/haikuports" target="_BLANK">recipes</a> known to the Haiku package build system</p>
	<div style="float: right; margin-top: -50px">
	<%= form_tag recipes_path, method: 'get' do %>
	    <%= text_field_tag(:search) %>
	    <%= submit_tag("Search", :name => nil) %>
	<% end %>
	</div>
</div>

<center>
<table class="table table-striped table-hover table-condensed" style='width: 100%;'>
  <thead>
	<tr>
		<th>Name</th>
		<th width="128px">Category</th>
		<th width="256px">Version</th>
		<th width="42px">Rev.</th>
		<th width="64px">Lint</th>
		<% @architectures.each do |arch| %>
			<th width="64px"><%= arch[:name] %></th>
		<% end %>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= image_tag "icons/document-task.png" %><%= link_to recipe.name, recipe %></td>
        <td><%= recipe.category %></td>
        <td><%= recipe.version %></td>
        <td><%= recipe.revision %></td>
        <td><%= lint_icon(recipe) %></td>
        <% @architectures.each do |arch| %>
          <% package = recipe.packages.find{ |p| p.architecture_id == arch.id} %>
          <td><%= package_icon(package) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</center>

<%= page_entries_info @recipes %>
<%= will_paginate @recipes, renderer: BootstrapPagination::Rails %>

<br>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<div class='row'>
  <div class='col-md-12'>
    <span style="font-size: 1.5em; font-weight: bold;"><%=@recipe.name %></span>
    <span style="font-size: 0.8em"><%= @recipe.version %> (revision <%= @recipe.revision %>)</span>
  </div>
</div> <!-- row -->

<div class='row'>
  <div class='col-md-7'>
    <div class="panel panel-default">
  	<div class="panel-heading">Information</div>
  	<div class="panel-body">
        <div style="padding: 10px;">
          <strong>Category:</strong>
          <%= @recipe.category %><br/>
          <strong>Filename:</strong>
          <%= @recipe.filename %><br/>
          <strong>Lint:</strong>
          <%=raw @recipe[:lintret] == 0 ? "<span style='color: green'>Passing</span>" : "<span style='color: red'>Failing</span>" %>
        </div>
      </div>
    </div>
  </div>
  
  <div class='col-md-5'>
    <div class="panel panel-default">
      <div class="panel-heading">Packages</div>
      <div class="panel-body">
        <table class="table table-striped-column table-condensed" style='width: 100%; margin-bottom: 0px;'>
          <thead>
            <tr>
  			<% @architectures.each do |arch| %>
  			  <th style="text-align: center;"><b><%= arch.name %></b></th>
  			<% end %>
            </tr>
          </thead>
          <tbody>
  		    <tr>
  		      <% @recipe.packages.joins(:architecture).each do | package | %>
                <td style="text-align: center;"><%= package_icon(package, 32) %><br/>
  		        <span style='font-size: 0.8em;'><%= (package.latestrev != 0 ? package.latestrev : "none") %></span>
				</td>
  		        </td>
  		      <%-end-%>
  		    </tr>
  	      </tbody>
        </table>
      </div>
    </div>
  </div>
</div> <!-- end row -->

<div class="row">
  <div class='col-md-12'>
    <div class="panel panel-default">
      <div class="panel-heading">Builds Results (last 10)</div>
      <div class="panel-body">
        <table class="table table-striped table-hover table-condensed" style='width: 100%;'>
          <thead>
        	<tr>
              <td>Build</td><td>Builder</td><td>Architecture</td><td>Start date</td><td>End date</td><td>Result</td>
            </tr>
          </thead>
          <tbody>
            <% if @recipe.builds.count == 0 %>
              <tr><td colspan=6><center>No builds found</center></td></tr>
            <% end %>
            <% @recipe.builds.order('issued DESC').limit(10).each do | build | %>
        	  <tr>
              <td><%= link_to "##{build['id']}", build %></td>
              <td><%= link_to build.builder['hostname'], build.builder %></td>
              <td><%= build.architecture['name'] %></td>
              <td><%= build['issued'] %></td>
              <td><%= build['completed'] %></td>
              <td><%=raw build_state(build) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div> <!-- row -->

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">Current Recipe</div>
      <div class="panel-body">
        <div class="CodeRay">
        <pre><%=raw CodeRay.scan_file("#{Rails.root.join("cache")}/repos/ports.git#{@recipe.filename}", :recipe).html %></pre>
        </div>
      </div>
    </div>
  </div>
</div> <!-- row -->

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">Lint Results</div>
      <div class="panel-body">
        <%=raw @recipe[:lintret] ? @recipe[:lint] : "<span style='color: red; font-weight: bold'> Error: Missing lint data!</span>" %>
      </div>
    </div>
  </div>
</div> <!-- row -->