config/routes.rb
Rails.application.routes.draw do
  get 'help/builders'
  get 'help/recipes'
  get 'help/repos'
  get 'help/builds'
  get 'help', to: 'help#index'

  mount API::Root => '/'

  resources :builds
  resources :builders

  get '/builders/:hostname/getwork', to: 'builders#getwork'
  post '/builders/:hostname/putwork', to: 'builders#putwork'
  #match '/builders(/:hostname)/getwork', :action => 'getwork', via: [:get], :controller => :builders

  resources :repos
  resources :recipes, only: [:index, :show], id: /[A-Za-z0-9\.\-_\+~]+?/, format: false

  root 'recipes#index'
end

app/models/build.rb
class Build < ActiveRecord::Base
  belongs_to :builder
  belongs_to :architecture
  belongs_to :recipe
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :set_build, only: [:show, :edit, :update, :destroy]

  # GET /builds
  # GET /builds.json
  def index
    @builds = Build.all.order(issued: :desc).page(params[:page])
  end

  # GET /builds/1
  # GET /builds/1.json
  def show
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_build
    @build = Build.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def build_params
    params.require(:build).permit(:architecture_id, :builder_id, :recipe_id, :issued, :completed, :result)
  end
end

app/helpers/builds_helper.rb
module BuildsHelper
  def build_state(build)
    if build.active == true
      return "<span style='font-weight: bold; color: #9999ff;'>Building...</span>"
    end

    if build.result == 0
      return "<span style='font-weight: bold; color: #00ff00;'>Successful</span>"
    end

    return "<span style='font-weight: bold; color: #ff0000;'>Failed</span>"
  end
end

app/views/builds/_form.html.erb
<%= form_for(@build) do |f| %>
  <% if @build.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@build.errors.count, "error") %> prohibited this build from being saved:</h2>

      <ul>
      <% @build.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :architecture_id %><br>
    <%= f.number_field :architecture_id %>
  </div>
  <div class="field">
    <%= f.label :builder_id %><br>
    <%= f.number_field :builder_id %>
  </div>
  <div class="field">
    <%= f.label :recipe_id %><br>
    <%= f.number_field :recipe_id %>
  </div>
  <div class="field">
    <%= f.label :issued %><br>
    <%= f.datetime_select :issued %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.datetime_select :completed %>
  </div>
  <div class="field">
    <%= f.label :result %><br>
    <%= f.text_area :result %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/builds/edit.html.erb
<h1>Editing build</h1>

<%= render 'form' %>

<%= link_to 'Show', @build %> |
<%= link_to 'Back', builds_path %>

app/views/builds/index.html.erb
<p id="notice"><%= notice %></p>

<div class="title">
  <h2>Builds</h2>
  <p>This is a listing of package builds that have been issued.</p>
</div>

<center>
<table class="table table-striped table-hover table-condensed" style='width: 100%;'>
  <thead>
    <tr>
      <th>ID</th>
      <th>Architecture</th>
      <th>Builder</th>
      <th>Recipe</th>
      <th>Version</th>
      <th>Revision</th>
      <th>Issued</th>
      <th>Completed</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @builds.each do |build| %>
      <tr>
        <td><%= link_to "##{build.id}", build %></td>
        <td><%= build.architecture['name'] %></td>
        <td><%= link_to build.builder['hostname'], build.builder %></td>
        <td><%= link_to build.recipe['name'], build.recipe %></td>
        <td><%= build.recipe['version'] %></td>
        <td><%= build.recipe['revision'] %></td>
        <td><%= build.issued %></td>
        <td><%= build.completed ? build.completed : "never" %></td>
        <td><%=raw build_state(build) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= page_entries_info @builds %>
<%= will_paginate @builds, renderer: BootstrapPagination::Rails %>

app/views/builds/new.html.erb
<h1>New build</h1>

<%= render 'form' %>

<%= link_to 'Back', builds_path %>

app/views/builds/show.html.erb
<p id="notice"><%= notice %></p>

<div class='row'>
  <div class='col-md-12'>
  <h2>Build #<%= @build.id %></h2>
  </div>
</div>

<div class='row'>
  <div class='col-md-12'>
    <div class="panel panel-default">
    <div class="panel-heading">Build Info</div>
    <div class="panel-body">
    <table class="table table-striped  table-condensed table-hover" style='width: 100%;'>
      <tr><td>Recipe</td><td><%= link_to "#{@build.recipe['name']}-#{@build.recipe['version']}", @build.recipe %></td></tr>
      <tr><td>Status</td><td><%=raw build_state(@build) %></td></tr>
      <tr><td>Issued</td><td><%= time_ago_in_words(@build.issued) %> ago (<%=@build.issued%>)</td></tr>
      <tr><td>Completed</td><td><%= @build.completed ? @build.completed : "never"%></td></tr>
    </table>
    </div>
    </div>
  </div>
</div>

<%if @build.result%>
<div class='row'>
  <div class='col-md-12'>
    <div class="panel panel-default">
    <div class="panel-heading">Results</div>
    <div class="panel-body">
      <div class="CodeRay"><pre><%= @build.details.gsub(/\n/, '<br>').html_safe %></pre></div>
    </div>
    </div>
  </div>
</div>
<%end%>